package demoorg.demoproj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DemoObj implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DemoObj() {
    }

}